baseURL = "http://localhost.cloudposse.com:1313/"
languageCode = "en-us"
title = "Cloud Posse Developer Hub"
theme = "hugo-theme-docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

#SEO
enableRobotsTXT = true
canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

publishDir = "public"

enableEmoji = true
# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
#
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"

[params]
showVisitedLinks = true # default is false
themeStyle = "flex"
ordersectionsby = "weight" 
# ordersectionsby = "title"
disableHomeIcon = true
disableSearch = true
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true
editURL = "https://github.com/cloudposse/docs/blob/master"
gtmContainerId = "GTM-WQWH2XV"

[outputFormats.glossary]
baseName = "glossary"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[mediaTypes]
  [mediaTypes."application/algolia"]
    suffix = "algolia.json"

[outputFormats.algolia]
isPlainText = true
mediaType = "application/algolia"
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "algolia"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-book'></i> <label>Documentation</label>"
identifier = "nav-documentation"
url = "/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Announcements</label>"
identifier = "nav-announcements"
url = "/announcements/"
weight = 20

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fab fa-github'></i> <label>Our GitHub</label>"
identifier = "nav-github"
url = "https://github.com/cloudposse/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>Blog</label>"
identifier = "nav-blog"
url = "https://cloudposse.com/blog/"
weight = 40

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-question'></i> <label>FAQ</label>"
identifier = "nav-faq"
url = "/faq/"
weight = 45

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-question'></i> <label>Support</label>"
identifier = "nav-support"
url = "https://cloudposse.com/commercial-support"
weight = 50

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-edit'></i> <label>Ask a Question</label>"
identifier = "nav-ask-a-question"
url = "/documentation/question/"
weight = 60

[[menu.shortcuts]]
name = "<i class='fa fa-envelope'></i> <label>Contact Us</label>"
url = "/documentation/contact-us/"
identifier = "nav-contact-us"
weight = 70


[related]

# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 60

# To get stable "See also" sections we, by default, exclude newer related pages. (set to false)
includeNewer = true

# Will lower case keywords in both queries and in the indexes.
toLower = true

[[related.indices]]
name = "keywords"
weight = 150

[[related.indices]]
name  = "author"
toLower = true
weight = 30

[[related.indices]]
name  = "tags"
weight = 100

[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
